//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonwealthGames.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int id { get; set; }
        public int productId { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<decimal> price { get; set; }
        public string description { get; set; }
        public string companyName { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
